# Generated by Django 5.2.6 on 2025-09-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'Kunde'), ('supplier', 'Lieferant'), ('general', 'Allgemein')], default='customer', max_length=20, verbose_name='Typ')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Straße und Nr.')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz')),
                ('postal_code', models.CharField(max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Ort')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Bundesland')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('vat_id', models.CharField(blank=True, max_length=32, verbose_name='USt-IdNr.')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Funktion')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobil')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptansprechpartner')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.address', verbose_name='Adresse')),
            ],
        ),
    ]
