# Generated by Django 5.2.6 on 2025-09-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name'], 'verbose_name': 'Adresse', 'verbose_name_plural': 'Adressen'},
        ),
    ]
